### PR TITLE
Fixes: Custom API Auth headers in Paw + Postman Pathname Bug

### LINKED ISSUE #34: apiKey securityDefinition is not respecting header key
Trying to import this swagger definition https://gist.github.com/databus23/848f60539956284e504605d4d9c01bc1

I noticed that the securityDefinition is not correctly mapped:
image

It seems the header name is ignored. It should be `X-Auth-Token` not `Authorization`.

This is unfortunate because I need to change it for every request after importing it.

### PR DESCRIPTION
**Pull request by JonathanMontane**
Should fix https://github.com/luckymarmot/Paw-SwaggerImporter/issues/34

### CODE REVIEW

**Comment by JonathanMontane** [comment]
Should fix https://github.com/luckymarmot/Paw-PostmanCollectionV2Importer/issues/2

**Comment by JonathanMontane** [comment]
- [x] fixes missing Postman imports in `node`, `web` and `webworker`
- [x] normalizes Postman format names to `postman-collection`

**Comment by JonathanMontane** [comment]
- [x] loaders now default to fsResolution instead of httpResolution in case of unknown protocol
- [x] normalizes loaders behavior

**Comment by caffeineflo** [comment]
Hey @JonathanMontane,

thanks for getting back to me so quickly, I unfortunately wasn't that quickly testing your branch ... sorry!

Now that I finally got back to look into this, I tried reimporting the same Postman Collection again and I ended up getting a different error:

`variable.createDynamicString is not a function. (In 'variable.createDynamicString()', 'variable.createDynamicString' is undefined)`

**Comment by JonathanMontane** [comment]
@caffeineflo I'm looking into what may be causing this issue.

Are you by any chance using the `noauth` authentication type in your collection? This might be what is causing issues. I'm looking into how to fix this.

**Comment by caffeineflo** [comment]
@JonathanMontane No `noauth` in my collection.

What I've been wondering, are you using any kind of new API-Flow version that I don't have access to? I've been searching through the API-Flow source and your code is the only one that uses `variable.createDynamicString` hence I'm wondering if I'm missing a commit that defines `createDynamicString`

**Comment by JonathanMontane** [comment]
@caffeineflo `createDynamicString` is a method associated with variables that is exposed by Paw to the JS environment, which is why its definition is not inside the code (it's written in OBJ-C inside Paw).

I'll keep looking into what may be causing this bug then.

**Comment by caffeineflo** [comment]
Hey @JonathanMontane ,

I was wondering if there's anything I can do to help you debug this issue from my side?

**Review by mittsh — APPROVED** [review]
Looks great and works nicely. Thanks so much @JonathanMontane 👍 

@caffeineflo thank you for the bug report! I have found and have been able to solve the bug (`variable.createDynamicString is not a function`). I'll do another PR for this one.

✌️

**Comment by mittsh** [comment]
@caffeineflo FYI I have fixed the bug in PR #143, I'll release a new Postman Importer and Swagger Importer shortly.

**Pull request merged**
